spring.application.name=compradoor

# 1. Configuración de la Base de Datos
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mi_base_de_datos}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:password}

# 2. Configuración de JPA/Hibernate (Importante)
# Le dice a Hibernate que hable en dialecto de Postgres
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
# "update" creará/actualizará las tablas basado en tus @Entity (ideal para desarrollo)
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

