spring.application.name=compradoor

# --- 1. CONFIGURACION BASE DE DATOS (POSTGRESQL) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mi_base_de_datos}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:password}

# --- 2. CONFIGURACION JPA/HIBERNATE ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- 3. CONFIGURACION ARCHIVOS Y VISTAS ---
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuracion para GROQ (Gratis)
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
#spring.ai.openai.api-key=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

